-- Downloads / Notices files module migration

CREATE TABLE IF NOT EXISTS downloads (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(220) NOT NULL,
    description TEXT DEFAULT NULL,
    category VARCHAR(100) DEFAULT NULL,
    file_path VARCHAR(255) NOT NULL,
    file_name VARCHAR(255) DEFAULT NULL,
    file_type VARCHAR(20) DEFAULT NULL,
    file_size VARCHAR(40) DEFAULT '0',
    uploaded_by INT DEFAULT NULL,
    uploaded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    visibility VARCHAR(20) NOT NULL DEFAULT 'public',
    download_count INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_downloads_category (category),
    INDEX idx_downloads_status (status),
    INDEX idx_downloads_uploaded_at (uploaded_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE downloads ADD COLUMN IF NOT EXISTS title VARCHAR(220) DEFAULT NULL;
ALTER TABLE downloads ADD COLUMN IF NOT EXISTS description TEXT DEFAULT NULL;
ALTER TABLE downloads ADD COLUMN IF NOT EXISTS category VARCHAR(100) DEFAULT NULL;
ALTER TABLE downloads ADD COLUMN IF NOT EXISTS file_path VARCHAR(255) DEFAULT NULL;
ALTER TABLE downloads ADD COLUMN IF NOT EXISTS file_name VARCHAR(255) DEFAULT NULL;
ALTER TABLE downloads ADD COLUMN IF NOT EXISTS file_type VARCHAR(20) DEFAULT NULL;
ALTER TABLE downloads ADD COLUMN IF NOT EXISTS file_size VARCHAR(40) DEFAULT '0';
ALTER TABLE downloads ADD COLUMN IF NOT EXISTS uploaded_by INT DEFAULT NULL;
ALTER TABLE downloads ADD COLUMN IF NOT EXISTS uploaded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE downloads ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active';
ALTER TABLE downloads ADD COLUMN IF NOT EXISTS visibility VARCHAR(20) NOT NULL DEFAULT 'public';
ALTER TABLE downloads ADD COLUMN IF NOT EXISTS download_count INT NOT NULL DEFAULT 0;
ALTER TABLE downloads ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
