CREATE TABLE IF NOT EXISTS `admissions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `application_id` varchar(20) NOT NULL,
  `full_name` varchar(100) NOT NULL,
  `father_name` varchar(100) NOT NULL,
  `dob` date NOT NULL,
  `gender` enum('Male','Female','Other') NOT NULL,
  `cnic` varchar(20) NOT NULL,
  `religion` varchar(50) DEFAULT 'Islam',
  `nationality` varchar(50) DEFAULT 'Pakistani',
  `phone` varchar(20) NOT NULL,
  `whatsapp` varchar(20) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `address` text NOT NULL,
  `prev_institution` varchar(255) NOT NULL,
  `matric_roll` varchar(20) DEFAULT NULL,
  `matric_year` varchar(10) DEFAULT NULL,
  `matric_total` int(11) DEFAULT 1100,
  `matric_obtained` int(11) DEFAULT NULL,
  `matric_grade` varchar(5) DEFAULT NULL,
  `board_name` varchar(100) DEFAULT NULL,
  `program` varchar(100) NOT NULL,
  `campus` varchar(100) NOT NULL,
  `session` varchar(20) DEFAULT '2026-2028',
  `photo` varchar(255) NOT NULL,
  `matric_certificate` varchar(255) NOT NULL,
  `cnic_copy` varchar(255) NOT NULL,
  `status` enum('Pending','Approved','Rejected') DEFAULT 'Pending',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `application_id` (`application_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `admission_applications` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `application_id` varchar(30) NOT NULL,
  `full_name` varchar(150) NOT NULL,
  `father_name` varchar(150) NOT NULL,
  `dob` date NOT NULL,
  `gender` varchar(20) NOT NULL,
  `cnic` varchar(30) NOT NULL,
  `religion` varchar(50) DEFAULT 'Islam',
  `nationality` varchar(50) DEFAULT 'Pakistani',
  `phone` varchar(30) NOT NULL,
  `whatsapp` varchar(30) DEFAULT NULL,
  `email` varchar(150) DEFAULT NULL,
  `address` text NOT NULL,
  `prev_institution` varchar(255) NOT NULL,
  `matric_roll` varchar(50) DEFAULT NULL,
  `matric_year` varchar(20) DEFAULT NULL,
  `matric_total` int(11) DEFAULT 1100,
  `matric_obtained` int(11) DEFAULT NULL,
  `matric_grade` varchar(20) DEFAULT NULL,
  `board_name` varchar(120) DEFAULT NULL,
  `program` varchar(120) NOT NULL,
  `campus` varchar(120) NOT NULL,
  `session` varchar(30) DEFAULT '2026-2028',
  `photo` varchar(255) NOT NULL,
  `matric_certificate` varchar(255) NOT NULL,
  `cnic_copy` varchar(255) NOT NULL,
  `payment_method` varchar(50) DEFAULT 'Cash',
  `transaction_id` varchar(120) DEFAULT NULL,
  `admission_fee` decimal(10,2) DEFAULT 5000.00,
  `status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `remarks` text DEFAULT NULL,
  `student_id` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `reviewed_by` int(11) DEFAULT NULL,
  `reviewed_at` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `application_id` (`application_id`),
  KEY `idx_admission_applications_status` (`status`),
  KEY `idx_admission_applications_cnic` (`cnic`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `whatsapp_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `phone` varchar(30) NOT NULL,
  `message_type` varchar(80) NOT NULL,
  `status` varchar(30) NOT NULL,
  `response` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_whatsapp_logs_phone` (`phone`),
  KEY `idx_whatsapp_logs_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
